# Generated by Django 4.2.12 on 2024-07-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_profile_age_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
