# Generated by Django 4.2.12 on 2024-07-05 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_delete_comment_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=255, unique=True)),
                ('show_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('listed_in', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
