# Generated by Django 4.2.12 on 2024-10-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_cake_image_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='available_quantity',
        ),
    ]
