# Generated by Django 4.2.12 on 2024-10-08 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=255)),
                ('design_details', models.TextField()),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
    ]
